[book]
authors = ["JorelAli"]
multilingual = false
src = "src"
title = "1.13 CommandAPI Documentation v3.1"

[build]
build-dir = "./../docs/3.1"

[output.html]
git-repository-url = "https://github.com/JorelAli/1.13-Command-API"
default-theme = "rust"
additional-css = ["style.css"]
additional-js = ["sidebar.js"]
mathjax-support = true

[output.html.fold]
enable = true