# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: snapshot-deploy

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  snapshot-deploy:
    needs: build # Only run if "build" succeeds
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          java-version: ${{ matrix.java }}
          cache: maven
          
    - name: deploy-maven
      run: |
        if mvn help:evaluate -Dexpression=project.version -q -DforceStdout | grep -E -q '\-SNAPSHOT$';  then
          echo "SNAPSHOT version detected: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          mvn deploy --batch-mode -P Platform.Bukkit,Platform.Velocity -DskipTests=true
        else
          echo "Version is not a SNAPSHOT version, not deploying to Sonatype Snapshot repo"
        fi
